# Generated by Django 5.2.15 on 2026-06-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['due_date', 'name']},
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='last_four_digits',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='paid',
        ),
    ]
