# Generated by Django 5.2.15 on 2026-06-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos', '0005_moneyaccount_expense_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhabit',
            options={'ordering': ['date', 'created_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['created_at', 'name']},
        ),
    ]
