# Generated by Django 5.2.15 on 2026-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos', '0006_alter_dailyhabit_options_alter_habit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['start_time', 'created_at', 'name']},
        ),
    ]
