# Generated by Django 5.2.15 on 2026-06-17 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_expense_transactions(apps, schema_editor):
    Expense = apps.get_model('lifeos', 'Expense')
    AccountTransaction = apps.get_model('lifeos', 'AccountTransaction')
    db_alias = schema_editor.connection.alias

    transactions = []
    for expense in Expense.objects.using(db_alias).iterator():
        transactions.append(
            AccountTransaction(
                user_id=expense.user_id,
                transaction_type='expense',
                title=expense.title,
                amount=expense.amount,
                from_account_id=expense.account_id,
                expense_id=expense.id,
                occurred_on=expense.spent_on,
                notes=expense.notes,
            )
        )
    AccountTransaction.objects.using(db_alias).bulk_create(transactions)


def remove_backfilled_expense_transactions(apps, schema_editor):
    AccountTransaction = apps.get_model('lifeos', 'AccountTransaction')
    AccountTransaction.objects.using(schema_editor.connection.alias).filter(transaction_type='expense').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos', '0007_alter_habit_options_habit_end_time_habit_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='lifeos.expense')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='lifeos.moneyaccount')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='lifeos.moneyaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.RunPython(backfill_expense_transactions, remove_backfilled_expense_transactions),
    ]
