# Generated by Django 5.2.15 on 2026-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos', '0008_accounttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('credit_card_payment', 'Credit Card Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moneyaccount',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('credit_card', 'Credit Card')], default='cash', max_length=20),
        ),
    ]
